import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as D from '../src/core.js';
import {AutomaticClueReader} from '../src/auto-read.js';
import {speechPreferences} from '../src/speech.js';
const lib=JSON.parse(fs.readFileSync(new URL('../data/library.json',import.meta.url)));
function fixture(){const session=D.createSession(lib,['pk1-2603-t4-l5']);const ctx={session,preferences:speechPreferences(),active:true,visible:true,writable:true};let calls=[];const reader=new AutomaticClueReader({context:()=>ctx,speak:text=>{calls.push(text);return true;},record:()=>D.addSupport(session,'listen',D.nowISO(),'automatic')});return{session,ctx,calls,reader};}
test('automatic clue defaults on for legacy settings but explicit false survives normalization',()=>{assert.equal(speechPreferences({speed:0.75}).autoReadClue,true);assert.equal(speechPreferences({autoReadClue:false}).autoReadClue,false);assert.equal(speechPreferences({autoReadClue:'false'}).autoReadClue,true);});
test('first render requests only the clue and does not create an attempt or first correct',async()=>{const f=fixture();assert.equal(await f.reader.read(),true);const q=D.activeQuestion(f.session);assert.deepEqual(f.calls,[q.question.question]);assert.equal(q.support[0].trigger,'automatic');assert.equal(q.attempts.length,0);assert.equal(q.firstCorrect,null);assert(D.validateSession(f.session));});
test('rerender, hint and wrong retry never automatically repeat the same clue',async()=>{const f=fixture();await f.reader.read();D.addSupport(f.session,'hint');D.submitAnswer(f.session,D.activeQuestion(f.session).question.options.find(o=>o.id!==D.activeQuestion(f.session).question.correctOptionId).id);await f.reader.read();await f.reader.read();assert.equal(f.calls.length,1);assert.equal(D.activeQuestion(f.session).support.filter(e=>e.trigger==='automatic').length,1);});
test('new question reads once; paused, hidden, read-only and parent contexts never read',async()=>{const f=fixture();for(const key of ['active','visible','writable']){f.ctx[key]=false;assert.equal(await f.reader.read(),false);f.ctx[key]=true;}f.ctx.preferences.autoReadClue=false;await f.reader.read();assert.equal(f.calls.length,0);f.ctx.preferences.autoReadClue=true;await f.reader.read();D.submitAnswer(f.session,D.activeQuestion(f.session).question.correctOptionId);assert.equal(await f.reader.read(),false);D.advance(f.session);D.pause(f.session);assert.equal(await f.reader.read(),false);D.resume(f.session);assert.equal(await f.reader.read(),true);assert.equal(f.calls.length,2);});
test('stored automatic evidence prevents repetition after controller recreation or resume',async()=>{const f=fixture();await f.reader.read();const again=new AutomaticClueReader({context:()=>f.ctx,speak:()=>{throw Error('must not speak again');},record:()=>false});assert.equal(await again.read(),false);const backup=D.validateBackup(JSON.stringify(D.makeBackup([f.session],lib)));assert.equal(backup.sessions[0].questions[0].support[0].trigger,'automatic');});
test('blocked/unavailable synchronous speech is not recorded and does not loop',async()=>{const f=fixture();let n=0;f.reader.speak=()=>{n++;return false;};await f.reader.read();await f.reader.read();assert.equal(n,1);assert.equal(D.activeQuestion(f.session).support.length,0);});
test('legacy listen events remain valid while duplicated automatic events are rejected',()=>{const f=fixture();D.addSupport(f.session,'listen');delete f.session.questions[0].support[0].trigger;assert(D.validateSession(f.session));assert(D.addSupport(f.session,'listen',D.nowISO(),'automatic'));assert.equal(D.addSupport(f.session,'listen',D.nowISO(),'automatic'),false);const q=D.activeQuestion(f.session);q.support.push({...q.support[1],id:D.uid()});assert.throws(()=>D.validateSession(f.session),/Duplicate automatic/);});
