import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import * as D from '../src/core.js';
import {loadCatalog,catalogFiles} from '../scripts/catalog.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
// Preserve the earlier source-import contract at its version boundary. Current corrections have separate tests.
const throughFile='data/lesson-packs/2026-10-06b-zip43.json';
const {library:lib,registry}=loadCatalog(root,{throughFile}),base=JSON.parse(fs.readFileSync(new URL('../data/library.json',import.meta.url)));
test('composed library keeps all base IDs and registers every declared source lesson',()=>{const declared=catalogFiles(root).filter(f=>f<=throughFile).reduce((n,f)=>n+JSON.parse(fs.readFileSync(root+f,'utf8')).lessons.length,base.lessons.length);assert.equal(lib.lessons.length,declared);assert.equal(lib.sources.length,declared);assert.equal(lib.topics.length,4);for(const i of base.items)assert(lib.items.some(x=>x.id===i.id));for(const l of base.lessons)assert.deepEqual(lib.lessons.find(x=>x.id===l.id),l);assert.equal(registry.records.length,lib.items.length);D.validateLibrary(lib);});
test('all seven weather lessons are complete after explicit parent resolutions',()=>{for(const l of lib.lessons.filter(l=>l.topicId==='weather'))assert(D.lessonReadiness(lib,l).ready);const phrase=lib.items.find(i=>i.id==='turning-green-bloom-pending');assert.equal(phrase.word,'Turning green Bloom');assert.equal(phrase.status,'ready');assert.equal(lib.items.filter(i=>i.id==='turning-green-bloom-pending').length,1);assert.equal(lib.items.find(i=>i.id==='light-pending').word,'Light rain');assert.equal(lib.items.find(i=>i.id==='heavy-pending').word,'Heavy rain');});
test('every full lesson plans every core/key target, including repetitions from other days',()=>{for(const l of lib.lessons){if(!D.lessonReadiness(lib,l).ready)continue;const s=D.createSession(lib,[l.id]);assert.deepEqual(new Set(s.questions.map(q=>q.question.itemId)),new Set(l.targets.map(t=>t.itemId)));D.validateSession(s);}const ids=['pk1-2603-t2-l1','pk1-2603-t2-l11'];for(const id of ids)assert(D.createSession(lib,[id]).questions.some(q=>q.question.itemId==='number-1'));});
test('letter forms, numbers and colour stimuli have four exact unique choices',()=>{const a=D.createSession(lib,['pk1-2603-t1-l9']);assert.equal(a.questions.filter(q=>q.question.mode==='letter').length,20);assert.equal(lib.items.filter(i=>i.question?.mode==='number').length,20);assert.equal(lib.items.filter(i=>i.question?.mode==='color').length,11);for(const i of lib.items)if(i.question)D.validateQuestion(i.question);});
test('clipped rows remain blocked without borrowing vocabulary from other days',()=>{for(const id of ['pk1-2603-t3-l5','pk1-2603-t3-l8','pk1-2603-t3-l11']){const l=lib.lessons.find(l=>l.id===id);assert(D.lessonReadiness(lib,l).unknownTotal);assert.throws(()=>D.createSession(lib,[id]),/unresolved/);assert(D.createSession(lib,[id],'review').questions.length>0);}assert(!lib.lessons.find(l=>l.id==='pk1-2603-t3-l8').targets.some(t=>t.itemId==='penguin'));});
test('source metadata conflict is explicit and the printed theme/name is not silently rewritten',()=>{const l=lib.lessons.find(l=>l.id==='pk1-2603-t1-l5');assert.equal(l.name,'PK1_1 - ABC Workshop_5');assert.equal(l.date,'2026-07-04');assert.match(l.sourceNotes,/Metadata conflict/);});
test('shared item snapshots use the selected lesson topic instead of the original authoring topic',()=>{const s=D.createSession(lib,['pk1-2603-t3-l1']);const q=s.questions.find(q=>q.question.itemId==='apple');assert.deepEqual(D.questionTopics(q.question),['colors']);const old=D.createSession(base,['pk1-2603-t1-l1']);delete old.questions[0].question.topicIds;assert.deepEqual(D.questionTopics(old.questions[0].question),['abc']);D.validateSession(old);});
test('legacy session snapshots and old backups stay interpretable after new content',()=>{const old=D.createSession(base,['pk1-2603-t4-l5']);D.submitAnswer(old,old.questions[0].question.correctOptionId);const saved=D.canonical(old);loadCatalog(root);assert.equal(D.canonical(old),saved);D.validateBackup(JSON.stringify(D.makeBackup([old],lib)));});
