import test from 'node:test';import assert from 'node:assert/strict';
import {SpeechController,chooseVoice,exactVoice,speechPreferences} from '../src/speech.js';
const v=(name,lang,local=true)=>({name,lang,localService:local,voiceURI:'device:'+name});
const gb=v('Fixture UK','en-GB'),us=v('Fixture US','en-US'),remote=v('Fixture remote','en-AU',false),fr=v('French','fr-FR');
const pref={speechLang:'en-GB',voiceURI:us.voiceURI,voiceName:us.name,voiceLang:us.lang,speed:0.75};
test('saved exact voice wins when online',()=>assert.equal(chooseVoice([gb,us],pref).voice,us));
test('missing saved voice falls back without overwriting preference',()=>{const before=JSON.stringify(pref);assert.equal(chooseVoice([gb],pref).voice,gb);assert.equal(JSON.stringify(pref),before);});
test('name and language resolve a renamed voice URI',()=>{const renamed={...us,voiceURI:'new-uri'};assert.equal(exactVoice([renamed],pref),renamed);});
test('accent then local English then other English then system',()=>{assert.equal(chooseVoice([remote,gb],{}).voice,gb);assert.equal(chooseVoice([remote,gb],{speechLang:'en-AU'}).voice,remote);assert.equal(chooseVoice([remote],{}).voice,remote);assert.equal(chooseVoice([fr],{}).voice,null);});
test('offline local preference overrides saved remote but retains preference',()=>{const p={...pref,voiceURI:remote.voiceURI,voiceName:remote.name,voiceLang:remote.lang};assert.equal(chooseVoice([remote,gb],p,true).voice,gb);assert.equal(p.voiceURI,remote.voiceURI);});
test('invalid speeds/accents fall back safely',()=>{assert.deepEqual(speechPreferences({speed:9,speechLang:'fr'}),speechPreferences());for(const speed of [0.75,0.9,1])assert.equal(speechPreferences({speed}).speed,speed);});
function fake(){const synth=new EventTarget(),win=new EventTarget(),doc=new EventTarget();doc.visibilityState='visible';let list=[],calls=[],timers=[],p=speechPreferences();synth.getVoices=()=>list;synth.cancel=()=>{};synth.speak=u=>calls.push(u);let changes=0;const controller=new SpeechController({synth,win,doc,Utterance:class{constructor(text){this.text=text;}},getPreferences:()=>p,timer:(fn,ms)=>{timers.push({fn,ms});return timers.length;},clear:()=>{},onChange:()=>changes++});return {controller,synth,win,doc,calls,timers,setVoices:x=>list=x,setPrefs:x=>p=x,get changes(){return changes;}};}
test('dynamic startup delayed voices and voiceschanged populate actual device list',()=>{const f=fake();f.controller.start();assert.equal(f.controller.voices.length,0);assert.deepEqual(f.timers.map(t=>t.ms),[250,1000,2500]);f.setVoices([gb,fr]);f.synth.dispatchEvent(new Event('voiceschanged'));assert.deepEqual(f.controller.voices,[gb]);f.setVoices([us]);f.timers[0].fn();assert.deepEqual(f.controller.voices,[us]);f.controller.destroy();});
test('foreground, manual refresh, and page resume refresh voices',()=>{const f=fake();f.controller.start();const before=f.changes;f.doc.dispatchEvent(new Event('visibilitychange'));f.win.dispatchEvent(new Event('pageshow'));f.controller.scheduleRefresh();assert(f.changes>=before+3);f.controller.destroy();});
test('test voice is standalone and reads current speed',()=>{const f=fake();f.setVoices([gb]);f.setPrefs({...pref,voiceURI:'',voiceName:'',speed:0.75});assert(f.controller.test());assert.equal(f.calls[0].rate,0.75);f.setPrefs({...pref,speed:1});f.controller.speak('Question');assert.equal(f.calls[1].rate,1);assert.equal(f.calls[0].voice,gb);assert.match(f.calls[0].text,/Hello/);});
test('missing or failed speech never crashes learning',()=>{const c=new SpeechController({synth:null,Utterance:null});assert.equal(c.test(),false);const f=fake();f.synth.speak=()=>{throw new Error('blocked');};assert.equal(f.controller.test(),false);});
