import * as D from './core.js';
import {Store} from './store.js';
import {AutomaticClueReader} from './auto-read.js';
import {ACCENTS,SPEEDS,SpeechController,exactVoice,speechPreferences} from './speech.js';
const $=id=>document.getElementById(id);
function el(tag,props={},...children){const n=document.createElement(tag);for(const [k,v]of Object.entries(props)){if(k==='class')n.className=v;else if(k==='on')for(const [name,fn]of Object.entries(v))n.addEventListener(name,fn);else if(k==='text')n.textContent=v;else if(k==='checked'||k==='disabled'||k==='hidden'||k==='selected')n[k]=Boolean(v);else n.setAttribute(k,String(v));}for(const child of children.flat(Infinity))if(child!==null&&child!==undefined)n.append(child instanceof Node?child:document.createTextNode(String(child)));return n;}
function button(text,fn,cls='',disabled=false){return el('button',{type:'button',class:cls,disabled,on:{click:()=>Promise.resolve().then(fn).catch(error)}},text);}
function field(label,node){return el('label',{class:'field'},el('span',{},label),node);}
function select(id,options,value,onchange){const n=el('select',{id,on:{change:e=>Promise.resolve(onchange(e.target.value)).catch(error)}});for(const [v,label]of options)n.append(el('option',{value:v},label));n.value=String(value);return n;}
function table(headers,rows){return el('div',{class:'table-scroll',tabindex:'0'},el('table',{},el('thead',{},el('tr',{},headers.map(h=>el('th',{scope:'col'},h)))),el('tbody',{},rows.map(row=>el('tr',{},row.map(cell=>el('td',{},cell)))))));}
function download(name,value,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}),url=URL.createObjectURL(blob),a=el('a',{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
function error(e){console.error(e);toast(e.message||String(e));}
const store=new Store();let library,registry,build,weeks,sessions=[],prefs={},reviews={},speech,autoReader,current=null,route='home',busy=false,dirty=false,offline=false;
let selected=new Set(),count='all',customCount=5,homeWeek='all',historyView='sessions',historyPage=0,historyFilters={from:'',to:'',topic:'',lesson:'',status:''},wordSearch='',galleryPage=0,galleryFilters={topic:'',status:'',search:''},lastTick=performance.now(),lastInteraction=performance.now();
store.onState=message=>{const n=$('storage-status');n.hidden=false;n.textContent=message;if(speech&&!busy&&!dirty){Promise.all([store.getPreferences(),store.readMeta('image-reviews',{}),reloadSessions()]).then(([p,r])=>{prefs=p;reviews=r;render();}).catch(error);}};
function locked(){return busy||dirty||!store.writer;}
function storageNotice(){if(store.memory){$('storage-status').hidden=false;$('storage-status').textContent='Temporary memory only. Export a full history backup before closing.';}else if(!store.writer){$('storage-status').hidden=false;$('storage-status').textContent='Read-only: another Rise_Voca tab is active. Close it, then wait up to 15 seconds before continuing.';}}
function updateNav(){const nav=$('navigation');nav.replaceChildren();nav.className='nav';for(const [key,label]of [['home','My lessons'],['review','Quick review'],['history','Learning History'],['parent','Parent & Settings']]){const b=button(label,()=>navigate(key),route===key?'selected':'');b.setAttribute('aria-current',route===key?'page':'false');nav.append(b);}}
function accountTime(s){const now=performance.now(),delta=Math.max(0,now-lastTick);if(route==='quiz'&&s?.status==='in-progress'&&!s.paused&&s.phase==='question'&&document.visibilityState==='visible'&&now-lastInteraction<60000)s.activeMs+=Math.min(delta,15000);lastTick=now;}
async function reloadSessions(){sessions=await store.allSessions();}
async function mutate(fn,{paint=true}={}){if(locked()||!current)return false;busy=true;const next=D.clone(current);accountTime(next);try{const changed=fn(next);if(changed===false){busy=false;return false;}current=await store.saveSession(next,current.revision);await reloadSessions();busy=false;if(paint)renderQuiz();return true;}catch(e){current=next;dirty=true;busy=false;$('storage-status').hidden=false;$('storage-status').textContent='Save failed. Learning is paused to protect your history. Export a full backup before closing. '+e.message;renderQuiz();return false;}}
async function navigate(next){speech?.cancel();if(route==='quiz'&&current?.status==='in-progress'&&!current.paused){if(!await mutate(s=>D.pause(s),{paint:false}))return;}route=next;lastTick=performance.now();await reloadSessions();render();}
function render(){updateNav();storageNotice();const root=$('content');root.replaceChildren();if(route==='quiz')renderQuiz();else if(route==='review')renderReview();else if(route==='history')renderHistory();else if(route==='parent')renderParent();else renderHome();}
function hero(kicker,title,copy,icon){return el('section',{class:'hero'},el('div',{},el('p',{class:'eyebrow'},kicker),el('h1',{},title),el('p',{},copy)),el('div',{class:'hero-emoji','aria-hidden':'true'},icon));}
function lessonDetails(l){const d=el('details',{},el('summary',{},'Words & parent-led speaking'));d.append(el('div',{class:'vocab-list'},l.targets.map(t=>{const i=library.items.find(x=>x.id===t.itemId);return el('span',{},i.word+' ('+t.role+')'+(i.status==='pending'?' - pending':''));})),el('p',{class:'help'},'Original class: '+l.classId+' | '+l.date),el('p',{class:'help'},l.sourceNotes));d.append(el('strong',{},'Source questions (not scored)'),...l.sourceQuestions.map(q=>el('p',{},q)),el('strong',{},'Source answer patterns'),...l.sourceAnswers.map(a=>el('p',{},a)),el('p',{class:'help'},l.reading));return d;}
function renderHome(){const root=$('content');root.append(hero('Little lessons, big smiles','Ready for a little adventure?','Choose the day you want to practise. Every full lesson includes all its core and key words.','\u2600\ufe0f'));
  const unfinished=sessions.filter(s=>s.status==='in-progress');if(unfinished.length){const card=el('section',{class:'card'},el('h2',{},'Continue your adventure'));for(const s of unfinished.slice().sort((a,b)=>b.lastActivityAt.localeCompare(a.lastActivityAt)))card.append(el('div',{class:'row between'},el('p',{},s.lessonNames.join('; ')+' - '+D.metrics(s).solved+'/'+s.questions.length+' solved'),button('Resume',()=>openSession(s.id),'primary',locked())));root.append(card);}
  root.append(field('Week',select('week-filter',[['all','All weeks'],...weeks.map(w=>[w.id,w.label])],homeWeek,v=>{homeWeek=v;render();})));
  for(const week of weeks.filter(w=>homeWeek==='all'||w.id===homeWeek)){root.append(el('h2',{class:'week-heading'},week.label,el('span',{class:'tag'},offline?'Saved for offline':'Included in offline pack')));const grid=el('div',{class:'grid'});for(const id of week.lessonIds){const l=library.lessons.find(x=>x.id===id),r=D.lessonReadiness(library,l);const visits=sessions.filter(s=>s.mode==='lesson'&&s.lessonIds[0]===id&&s.status==='completed'),solvedVisits=visits.filter(s=>D.metrics(s).solved===s.questions.length);grid.append(el('article',{class:'lesson'},el('div',{class:'row between'},el('span',{class:'tag'},l.date.split('-').reverse().join('/')),el('span',{class:'tag '+(r.ready?'green':'warning')},r.ready?r.required+' learning targets':r.unknownTotal?r.available+' confirmed; source incomplete':r.available+'/'+r.required+' available')),el('h3',{},l.title),el('p',{class:'code'},l.name),el('p',{class:'help'},solvedVisits.length?'All targets solved in '+solvedVisits.length+' full session(s).':visits.length?'A previous session ended with skipped items.':'Four choices. Gentle retries. Little breaks.'),!r.ready?el('p',{class:'notice'},'Full lesson waits for source clarification. Partial review is available; it does not complete this lesson.'):null,lessonDetails(l),el('div',{class:'row'},button(r.ready?'Let\'s learn':'Full lesson pending',()=>startSession([l.id],'lesson','all'),'primary',!r.ready||locked()),button('Review',()=>{selected=new Set([l.id]);return navigate('review');},'soft'))));}root.append(grid);}}
function eligible(mode='review'){try{return D.questionPool(library,[...selected],mode,mode==='practice'?D.practiceItemIds(sessions):null);}catch{return [];}}
function renderReview(){const root=$('content');root.append(hero('Mix, revisit, remember','A little review','Review is a sample, not a full lesson. Repeated words may be shared here, but never disappear from their own daily lesson.','\ud83c\udf08'));
  const icon=root.querySelector('.hero-emoji');if(icon)icon.textContent='\ud83c\udf08';
  const form=el('section',{class:'card'},el('h2',{},'Choose lessons'));const checks=el('div',{class:'checks'});for(const l of library.lessons){const input=el('input',{type:'checkbox',checked:selected.has(l.id),on:{change:e=>{if(e.target.checked)selected.add(l.id);else selected.delete(l.id);render();}}});checks.append(el('label',{class:'check'},input,el('span',{},l.name+' - '+l.date)));}form.append(el('div',{class:'row'},button('Select all',()=>{selected=new Set(library.lessons.map(l=>l.id));render();},'soft'),button('Clear',()=>{selected.clear();render();})),checks);const pool=eligible(),practice=eligible('practice');
  form.append(el('p',{class:'help'},pool.length+' eligible distinct answers/forms. '+practice.length+' items need more practice in the selected lessons. Unresolved source targets are excluded from partial review.'));
  form.append(field('Number of questions',select('review-count',[['all','All'],...['5','10','15','20'].map(n=>[n,n]),['custom','Custom']],count,v=>{count=v;render();})));
  if(count==='custom')form.append(field('Custom count (1-'+pool.length+')',el('input',{id:'custom-count',type:'number',min:'1',max:pool.length,value:customCount,on:{input:e=>customCount=Number(e.target.value)}})));
  form.append(el('div',{class:'actions'},button('Start quick review',()=>startSession([...selected],'review',count==='custom'?customCount:count),'primary',locked()||!pool.length),button('Practise tricky words',()=>startSession([...selected],'practice','all'),'warn',locked()||!practice.length)));root.append(form);}
async function startSession(ids,mode,n){if(locked())return;busy=true;try{const s=D.createSession(library,ids,mode,n,mode==='practice'?D.practiceItemIds(sessions):null);for(const q of s.questions)q.question.illustration=D.clone(registry.records.find(i=>i.id===q.question.visualId));current=await store.saveSession(s,0);await reloadSessions();busy=false;route='quiz';lastTick=performance.now();lastInteraction=performance.now();render();}catch(e){busy=false;error(e);}}
async function openSession(id){if(locked())return;current=D.clone(sessions.find(s=>s.id===id));route='quiz';await mutate(s=>D.resume(s),{paint:false});lastTick=performance.now();lastInteraction=performance.now();render();}
function reviewKey(img){return img.itemId+'|'+img.identity;}
function imageState(img){if(!img)return 'missing';return reviews[reviewKey(img)]?.decision||img.status;}
function usable(img){return ['approved','retained-reference','non-pictorial'].includes(imageState(img));}
function scene(img,{preview=false,mode='context'}={}){const box=el('div',{class:'scene'}),show=img&&(preview||usable(img))&&img.kind!=='missing';const ring=el('div',{class:'scene-ring'});if(show){if(img.kind==='color'){const swatch=el('span',{class:'colour-patch','aria-label':'Colour patch'});if(/^#[0-9a-f]{6}$/i.test(img.visual))swatch.style.backgroundColor=img.visual;ring.append(swatch);}else if(img.kind==='rain'){const rain=el('div',{class:'rain-stimulus '+(img.visual==='heavy'?'heavy':'light')},el('span',{},'\u2601\ufe0f'));const drops=el('div',{class:'rain-drops'});for(let n=0;n<(img.visual==='heavy'?16:3);n++)drops.append(el('span',{},'\ud83d\udca7'));rain.append(drops);ring.append(rain);}else if(img.kind==='css'){const art=el('div',{class:'css-art'});if(['mitten','fan','fireplace'].includes(img.visual))art.append(el('div',{class:img.visual},img.visual==='fireplace'?'\ud83d\udd25':''));ring.append(art);}else if(img.kind==='temperature'){const art=el('div',{class:'css-art'}),thermo=el('div',{class:'thermometer '+(img.visual==='cool'?'cool':'')});thermo.style.setProperty('--temperature',img.visual==='warm'?'70%':'38%');art.append(thermo);ring.append(art);}else{const text=String(img.visual||''),node=el('span',{class:'scene-main '+(['letter','number'].includes(img.kind)?'letter':Array.from(text).length>5?'multiple':'')},text);ring.append(node);}if(img.sparkOne)box.append(el('span',{class:'scene-spark'},img.sparkOne));if(img.sparkTwo)box.append(el('span',{class:'scene-spark second'},img.sparkTwo));}else ring.append(el('span',{class:'scene-main','aria-hidden':'true'},'\u2b50'));
  box.append(ring);if(show&&['letter','number'].includes(mode)){box.setAttribute('role','img');box.setAttribute('aria-label',(mode==='letter'?'Letter shown: ':'Numeral shown: ')+img.visual);}else if(show){box.setAttribute('aria-hidden','true');}if(!show)box.append(el('p',{class:'scene-note'},'Listen to the clue. Picture not yet approved.'));return box;}
function renderQuiz(){updateNav();if(current&&!D.canAnswer(current))speech?.cancel();const root=$('content');root.replaceChildren();if(!current){route='home';render();return;}const s=current,m=D.metrics(s);root.append(el('div',{class:'toolbar'},el('span',{class:'help'},s.lessonNames.join('; ')+' | '+s.mode),button('Save & pause',()=>navigate('home'),'soft',locked()||s.status!=='in-progress')));
  if(dirty){root.append(el('section',{class:'card'},el('h2',{},'Your session needs a backup'),button('Back up all history',backupAll,'primary')));return;}
  if(s.status!=='in-progress'){renderFinish(root);return;}
  if(s.paused){root.append(el('section',{class:'card finish'},el('div',{class:'trophy'},'\ud83c\udf1f'),el('h1',{},'A little pause'),el('p',{},'Your answers are safe on this device.'),button('Continue',()=>mutate(x=>D.resume(x)),'primary',locked())));return;}
  if(s.phase==='break'){root.append(el('section',{class:'card finish'},el('div',{class:'trophy'},'\ud83c\udf1f'),el('h1',{},'Time for a tiny stretch!'),el('p',{class:'help'},'Move your arms and take a breath. '+(s.questions.length-s.index)+' more questions when you are ready.'),button('Continue to round '+(Math.floor(s.index/s.roundSize)+1),()=>{lastInteraction=performance.now();return mutate(x=>D.continueRound(x));},'primary',locked())));return;}
  const q=D.activeQuestion(s),question=q.question,answered=Boolean(q.firstCorrect),round=Math.floor(s.index/s.roundSize)+1;
  root.append(el('section',{class:'progress-card'},el('div',{},el('div',{class:'progress-copy'},el('span',{},'Question '+(s.index+1)+' of '+s.questions.length),el('span',{},'Round '+round+' / '+Math.ceil(s.questions.length/s.roundSize))),el('progress',{max:s.questions.length,value:s.index,'aria-label':'Questions visited'})),el('div',{class:'score'},'\u2b50 '+m.firstTry+' / '+m.planned)));
  const panel=el('div',{class:'question-panel'}),shell=el('section',{class:'quiz-shell'},scene(question.illustration,{mode:question.mode}),panel);
  const tools=el('div',{class:'question-tools'}),listen=el('button',{id:'listen',type:'button',class:'soft','aria-keyshortcuts':'Space',disabled:locked()||answered,on:{click:listenQuestion}},'Listen');tools.append(listen,field('Speed',select('quiz-speed',SPEEDS.map(v=>[v,String(v)+'x']),prefs.speed,v=>saveSettings({...prefs,speed:Number(v)}))));panel.append(el('p',{class:'eyebrow'},'Choose the best answer'),tools,el('p',{class:'shortcut'},'1-4 = Answer | Space = Listen | Ctrl = Hint'),el('h1',{id:'question-text'},question.question));if(question.translation)panel.append(el('p',{class:'translation',lang:'vi'},question.translation));
  const answers=el('div',{class:'answers'});for(const [i,o]of question.options.entries()){const b=button('',()=>answer(o.id),'answer'+(answered&&o.id===question.correctOptionId?' correct':q.attempts.at(-1)?.optionId===o.id&&!answered?' wrong':''),locked()||answered);b.id='answer-'+i;b.dataset.optionId=o.id;b.setAttribute('aria-keyshortcuts',String(i+1));b.append(el('span',{'aria-hidden':'true'},String(i+1)),el('span',{},o.label));answers.append(b);}panel.append(answers);
  if(answered)panel.append(el('div',{class:'feedback success',role:'status'},'Yes! '+question.word+' is right. '+question.explanation));else if(q.support.some(e=>e.kind==='hint'))panel.append(el('div',{class:'feedback',role:'status'},question.hint));else if(q.attempts.length)panel.append(el('div',{class:'feedback try-again',role:'status'},'Almost! Try again. Take your time.'));
  panel.append(el('div',{class:'actions'},button(q.support.some(e=>e.kind==='hint')?'Hint is open':'Show a hint',()=>mutate(x=>D.addSupport(x,'hint')),'warn',locked()||answered),answered?button(s.index===s.questions.length-1?'See my result':'Next word',()=>{speech.cancel();return mutate(x=>D.advance(x));},'primary',locked()):button('Skip for now',()=>{speech.cancel();return mutate(x=>D.skipQuestion(x));},'',locked())));
  root.append(shell);updateSpeechControls();queueMicrotask(()=>autoReader?.read().catch(error));}
let lastAnswerAt=-Infinity;
async function answer(optionId){const time=performance.now();if(time-lastAnswerAt<350||locked())return;lastAnswerAt=time;const accepted=await mutate(s=>D.submitAnswer(s,optionId));if(accepted&&D.activeQuestion(current).firstCorrect)speech.speak(D.activeQuestion(current).question.word+'.');}
function listenQuestion(){if(locked()||!current||!D.canAnswer(current))return;speech.speak(D.activeQuestion(current).question.question);void mutate(s=>D.addSupport(s,'listen'));}
function renderFinish(root){const s=current,m=D.metrics(s),card=el('section',{class:'card finish'},el('div',{class:'trophy'},'\ud83c\udfc6'),el('h1',{},s.status==='completed'?'You did it!':'Well done for practising!'),el('p',{class:'help'},m.solved+' words solved; '+m.skipped+' skipped; '+m.unseen+' not yet seen. '+(s.mode==='lesson'&&m.solved===m.planned?'Every target in this lesson was solved.':m.solved===m.planned?'All selected review targets were solved. Daily lessons keep their own completion status.':'Skipped or unseen targets still need practice.')),el('div',{class:'score'},m.firstTry+' / '+m.planned+' first-try stars'),el('div',{class:'vocab-list'},s.questions.map(q=>el('span',{},q.question.word+' - '+D.outcome(q)))),el('pre',{class:'summary'},D.parentSummary(s)),el('div',{class:'row'},button('Copy parent summary',()=>copy(D.parentSummary(s)),'soft'),button('Play again',()=>startSession(s.lessonIds,s.mode,s.mode==='practice'?'all':s.requestedCount),'primary',locked()),button('My lessons',()=>navigate('home'))));root.append(card);}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied.');}catch{toast('Clipboard unavailable. Select the visible report text and copy it manually.');}}
async function saveSettings(value){if(locked())return;try{prefs=await store.savePreferences(speechPreferences(value));updateSpeechControls();toast(store.memory?'Voice preferences changed in temporary memory.':'Voice preferences saved.');}catch(e){updateSpeechControls();error(e);}}
function voiceKey(v){return JSON.stringify([v.voiceURI,v.name,v.lang]);}
function updateSpeechControls(){if(!speech)return;const voices=speech.voices,chosen=speech.selection(),voiceSelect=$('device-voice');for(const id of ['settings-speed','quiz-speed'])if($(id)){$(id).value=String(prefs.speed);$(id).disabled=!store.writer||dirty;}if($('auto-read-clue')){$('auto-read-clue').checked=prefs.autoReadClue;$('auto-read-clue').disabled=!store.writer||dirty;}if($('accent')){$('accent').value=prefs.speechLang;$('accent').disabled=!store.writer||dirty;}
  if(voiceSelect){const oldFocus=document.activeElement===voiceSelect;voiceSelect.replaceChildren(el('option',{value:''},'Automatic (follow accent preference)'));const saved=exactVoice(voices,prefs);if(!saved&&(prefs.voiceURI||prefs.voiceName))voiceSelect.append(el('option',{value:'unavailable',disabled:true},'Saved voice unavailable: '+(prefs.voiceName||prefs.voiceURI)));for(const v of voices)voiceSelect.append(el('option',{value:voiceKey(v)},v.name+' - '+v.lang+(v.localService?' - on-device':' - service voice')));voiceSelect.value=saved?voiceKey(saved):(prefs.voiceURI||prefs.voiceName)?'unavailable':'';voiceSelect.disabled=!store.writer||dirty;if(oldFocus)voiceSelect.focus({preventScroll:true});}
  if($('voice-status'))$('voice-status').textContent=voices.length+' English voices exposed. Using '+(chosen.voice?chosen.voice.name+' ('+chosen.voice.lang+')':'the browser/system default')+'; '+chosen.reason+'. '+(!navigator.onLine?'Offline: local English voices are preferred. ':'')+'On-device is a capability hint, not proof of audible offline playback.';
}
function voicePanel(){const box=el('section',{class:'card'},el('h2',{},'English Voice Settings'),el('p',{class:'help'},'Use the English voices actually available on this phone or tablet. Accent is the fallback preference when a specific voice is unavailable. No microphone is used.'));const a=select('accent',ACCENTS.map(x=>[x,x]),prefs.speechLang,v=>saveSettings({...prefs,speechLang:v}));const v=select('device-voice',[],'',value=>{const voice=speech.voices.find(x=>voiceKey(x)===value);return saveSettings({...prefs,voiceURI:voice?.voiceURI||'',voiceName:voice?.name||'',voiceLang:voice?.lang||''});});const speed=select('settings-speed',SPEEDS.map(x=>[x,x+'x']),prefs.speed,x=>saveSettings({...prefs,speed:Number(x)}));box.append(el('div',{class:'filters'},field('Preferred accent',a),field('Device voice',v),field('Speaking speed',speed)));box.append(el('label',{class:'check auto-read-setting'},el('input',{id:'auto-read-clue',type:'checkbox',checked:prefs.autoReadClue,on:{change:e=>saveSettings({...prefs,autoReadClue:e.target.checked})}}),el('span',{},'Automatically read each clue')),el('p',{class:'help'},'Read a newly presented clue once. If your browser blocks automatic speech, tap Listen. Automatic requests are labelled separately; they do not prove the child heard the audio.'));const test=el('button',{id:'test-voice',type:'button',class:'primary',on:{click:()=>speech.test()}},'Test voice');box.append(el('div',{class:'row'},test,button('Refresh voices',()=>speech.scheduleRefresh(),'soft')),el('p',{id:'voice-status',class:'help',role:'status'}),el('p',{id:'speech-status',class:'help',role:'status'}),el('p',{class:'help'},'Test voice does not create sessions, attempts, Listen events, or learning-history records. If Safari starts with an empty list, use Refresh voices after opening the app. A voice test must be repeated offline on your own device.'));return box;}
async function backupAll(){const all=await store.allSessions();if(current&&dirty){const i=all.findIndex(s=>s.id===current.id);if(i>=0)all[i]=current;else all.push(current);}download('rise-voca-full-history-'+new Date().toISOString().slice(0,10)+'.json',D.makeBackup(all,library));}
function exportReviews(){download('rise-voca-image-reviews.json',{kind:'image-reviews',schemaVersion:1,libraryFingerprint:library.fingerprint,exportedAt:D.nowISO(),scope:'all mappings and actual device decisions; not learning history',records:registry.records.map(img=>({itemId:img.itemId,identity:img.identity,defaultStatus:img.status,review:reviews[reviewKey(img)]||null}))});}
function missingImages(){return registry.records.filter(img=>img.status!=='non-pictorial'&&!usable(img)).map(img=>{const item=library.items.find(i=>i.id===img.itemId);return {itemId:item.id,word:item.word,meaning:item.meaning,sourceRefs:item.sourceRefs,state:imageState(img),reason:img.reason||'Candidate is not yet approved or was rejected.'};});}
function renderParent(){const root=$('content');root.append(hero('For parents','A helpful little corner','Voice settings, source words, backups and picture review. These tools never award learning credit.','\ud83d\udee0\ufe0f'),voicePanel());
  const exports=el('section',{class:'card'},el('h2',{},'Library & backups'),el('p',{class:'help'},'Library exports contain learning content, not progress. Full history backup includes all sessions, even unfinished ones, regardless of report filters. Settings and image reviews are separate exports.'));
  exports.append(el('div',{class:'export-grid'},button('Export library JSON',()=>download('rise-voca-library.json',library)),button('Library + image metadata',()=>download('rise-voca-library-images.json',{library,illustrations:registry,note:'Metadata and Unicode/CSS recipes; not embedded external image files.'})),button('Export all image reviews',exportReviews),button('Missing-image inventory',()=>download('rise-voca-missing-images.json',{libraryFingerprint:library.fingerprint,items:missingImages()})),button('Back up all history',backupAll,'primary'),button('Export voice preferences',()=>download('rise-voca-voice-preferences.json',{schemaVersion:1,exportedAt:D.nowISO(),preferences:prefs}))));
  const input=el('input',{id:'restore-file',type:'file',accept:'.json,application/json',class:'file-input',disabled:locked(),on:{change:async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>8*1024*1024)throw new Error('Backup exceeds 8 MiB.');const b=D.validateBackup(await file.text()),plan=D.mergePlan(await store.allSessions(),b.sessions);if(!confirm('Restore '+plan.additions.length+' new sessions and ignore '+plan.identical+' identical sessions? Conflicts will never be overwritten.'))return;const result=await store.restore(b);await reloadSessions();toast('Restored '+result.added+' sessions; '+result.identical+' identical sessions ignored.');}catch(ex){error(ex);}finally{e.target.value='';}}}});exports.append(field('Restore / merge a full history backup',input),el('p',{class:'help'},'This device only. There is no automatic phone/tablet sync. Device storage can be removed by the browser or by clearing site data; keep backups outside the app.'),button('Request persistent storage',async()=>toast(await navigator.storage?.persist?.()?'Persistent storage granted. Backups are still needed.':'Persistent storage was not granted or is unavailable. Keep backups.'),'soft'));root.append(exports);
  const install=el('section',{class:'card'},el('h2',{},'Installation & offline'),el('p',{class:'help'},'On iPhone/iPad: open the HTTPS site in Safari, tap Share, then Add to Home Screen. On Android: use Install app or Add to home screen in your browser menu. Downloaded HTML is not an installed PWA.'),el('p',{id:'offline-detail',class:'help'},offline?'App/content and native emoji/CSS are saved. Audio still requires a device test.':'Offline readiness has not yet been verified. Stay online and check again.'),el('div',{class:'row'},button('Check offline readiness',checkOffline,'soft'),button('Check for app updates',async()=>{const r=await navigator.serviceWorker?.getRegistration();await r?.update();toast('Update check requested. Save & pause, then close all app windows before reopening.');})),el('p',{class:'help'},'Updates never clear learning history. No automatic reload happens during a lesson. Build '+build.version+'; content '+library.contentVersion+'.'));root.append(install);
  const pending=el('section',{class:'card'},el('h2',{},'Source questions needing confirmation'));for(const a of library.ambiguities)pending.append(el('p',{},a.text+': '+a.reason));pending.append(el('p',{class:'help'},'Weather Report clarifications have been applied. Any newly clipped or ambiguous source rows remain explicitly flagged. Partial review never counts as a full lesson.'));root.append(pending);
  root.append(galleryPanel());updateSpeechControls();}
function galleryPanel(){const section=el('section',{class:'card',id:'illustration-review'},el('h2',{},'Review emoji & CSS illustrations'),el('p',{class:'help'},'Seven supplied emoji mappings are retained from the reference quiz. New cues need your review before appearing in lessons. Letter, numeral and solid-colour cards are intrinsic question content, not sourced pictures. A preview is not a learning attempt.'));
  const controls=el('div',{class:'filters'},field('Topic',select('image-topic',[['','All topics'],...library.topics.map(t=>[t.id,t.name])],galleryFilters.topic,v=>{galleryFilters.topic=v;galleryPage=0;refreshGallery();})),field('Review status',select('image-state',[['','All states'],...['needs-review','approved','rejected','missing','retained-reference','non-pictorial'].map(x=>[x,x])],galleryFilters.status,v=>{galleryFilters.status=v;galleryPage=0;refreshGallery();})),field('Word or meaning',el('input',{type:'search',id:'image-search',value:galleryFilters.search,on:{change:e=>{galleryFilters.search=e.target.value;galleryPage=0;refreshGallery();}}})));section.append(controls);
  const filtered=registry.records.filter(img=>{const i=library.items.find(x=>x.id===img.itemId);return (!galleryFilters.topic||(i.topicIds||[i.question?.topicId]).includes(galleryFilters.topic))&&(!galleryFilters.status||imageState(img)===galleryFilters.status)&&(i.word+' '+i.meaning).toLowerCase().includes(galleryFilters.search.toLowerCase());});const size=12,total=Math.ceil(filtered.length/size);galleryPage=Math.min(galleryPage,Math.max(0,total-1));const grid=el('div',{class:'gallery'});
  for(const img of filtered.slice(galleryPage*size,(galleryPage+1)*size)){const item=library.items.find(x=>x.id===img.itemId),card=el('article',{class:'image-card'},el('h3',{},item.word),el('p',{},item.meaning),el('span',{class:'tag'},imageState(img)));if(img.kind!=='missing')card.append(scene(img,{preview:true}));else card.append(el('p',{class:'notice'},img.reason));card.append(el('p',{},img.provider||'No provider selected'),el('p',{},'Identity: '+img.identity.slice(0,16)),el('p',{},img.attribution||'No candidate attached.'));if(img.kind!=='missing'&&img.status!=='non-pictorial')card.append(el('div',{class:'row'},button('Approve',()=>setReview(img,'approved'),'soft',locked()),button('Reject',()=>setReview(img,'rejected'),'',locked())));grid.append(card);}section.append(el('p',{class:'help'},filtered.length+' matching items. Source: native Unicode/original CSS only; no external image downloads in this release.'),grid,pagination(galleryPage,total,p=>{galleryPage=p;refreshGallery();}));return section;}
function refreshGallery(){const old=$('illustration-review');if(old)old.replaceWith(galleryPanel());}
async function setReview(img,decision){if(locked())return;reviews=await store.saveReview(reviewKey(img),{itemId:img.itemId,identity:img.identity,decision,at:D.nowISO()});refreshGallery();toast('Picture '+decision+'. This decision stays on this device.');}
function pagination(page,total,fn){return el('div',{class:'pagination'},button('Previous',()=>fn(page-1),'',page<=0),el('span',{class:'help'},total?'Page '+(page+1)+' / '+total:'No matches'),button('Next',()=>fn(page+1),'',page>=total-1));}
function historyScope(){return D.filterSessions(sessions,historyFilters);}
function renderHistory(){const root=$('content');root.append(hero('Small steps worth celebrating','Learning History','Only actual saved practice is shown. Dates use Asia/Ho_Chi_Minh and the device clock, not a verified server clock.','\ud83c\udf1f'));const card=el('section',{class:'card'});
  const changed=(key,value)=>{historyFilters[key]=value;historyPage=0;render();};card.append(el('div',{class:'filters'},field('Session start: From',el('input',{id:'history-from',type:'date',value:historyFilters.from,on:{change:e=>changed('from',e.target.value)}})),field('Session start: To (whole day)',el('input',{id:'history-to',type:'date',value:historyFilters.to,on:{change:e=>changed('to',e.target.value)}})),field('Actually studied topic',select('history-topic',[['','All topics'],...library.topics.map(t=>[t.id,t.name])],historyFilters.topic,v=>changed('topic',v))),field('Actually studied lesson',select('history-lesson',[['','All lessons'],...library.lessons.map(l=>[l.id,l.name])],historyFilters.lesson,v=>changed('lesson',v))),field('Session status',select('history-status',[['','All statuses'],['in-progress','In progress / paused'],['completed','Completed'],['ended-early','Ended early']],historyFilters.status,v=>changed('status',v)))));
  card.append(el('div',{class:'row'},button('Reset filters',()=>{historyFilters={from:'',to:'',topic:'',lesson:'',status:''};wordSearch='';historyPage=0;render();}),button('Back up all history',backupAll,'primary')));
  let rows;try{rows=historyScope();}catch(e){card.append(el('p',{class:'notice error'},e.message));root.append(card);return;}
  card.append(el('p',{class:'help'},rows.length+' matching sessions of '+sessions.length+'. Aggregates and CSVs inherit these session filters. Topic/lesson filters select sessions that actually encountered them, not unused selections.'),el('div',{class:'nav'},...['sessions','topics','words'].map(v=>button(v==='sessions'?'Sessions':v==='topics'?'By topic':'By word / item',()=>{historyView=v;historyPage=0;render();},v===historyView?'selected':''))));
  if(historyView==='sessions'){const page=rows.slice(historyPage*10,historyPage*10+10);card.append(button('Sessions CSV (filtered)',()=>sessionsCSV(rows),'soft'),table(['Started / status','Lesson(s) / mode','Progress','Evidence','Time','Open'],page.map(s=>{const m=D.metrics(s);return [el('span',{},D.localTime(s.startedAt),el('br'),s.status+(s.paused?' (paused)':'')),el('span',{},s.lessonNames.join('; '),el('br'),s.mode),m.seen+' seen; '+m.solved+' solved; '+m.skipped+' skipped; '+m.unseen+' unseen',m.firstTry+'/'+m.planned+' first-try (planned); '+m.unassisted+' unassisted; '+m.attempts+' attempts; '+m.hints+' hints; '+m.listens+' listens',Math.round(m.activeMs/1000)+'s active; '+Math.round(m.elapsedMs/1000)+'s elapsed',button('Details',()=>sessionDetails(s))];})),pagination(historyPage,Math.ceil(rows.length/10),p=>{historyPage=p;render();}));}
  else if(historyView==='words'){card.append(field('Search word or meaning',el('input',{id:'word-search',type:'search',value:wordSearch,on:{change:e=>{wordSearch=e.target.value;historyPage=0;render();}}})));const words=D.wordRows(rows,wordSearch);card.append(el('p',{class:'help'},words.length+' seen items. Needs practice = most recent seen outcome unsolved/skipped, more than one attempt, hint, or written-clue support. Listening alone is not a failure.'),button('Word-details CSV (filtered)',()=>wordsCSV(rows,wordSearch),'soft'),table(['Word / meaning','Seen sessions / correct','Attempts / support','First correct','Most recent','Practice'],words.slice(historyPage*15,historyPage*15+15).map(w=>[w.word+' / '+w.meaning,w.sessions+' / '+w.correct,w.attempts+' attempts; '+w.hints+' hints; '+w.listens+' listens',D.localTime(w.firstCorrect),D.localTime(w.lastActivity)+' / '+w.lastOutcome,w.needsPractice?'Needs practice':'No recent practice flag'])),pagination(historyPage,Math.ceil(words.length/15),p=>{historyPage=p;render();}));}
  else{const data=library.topics.map(t=>{const actual=rows.filter(s=>s.questions.some(q=>q.seenAt&&D.questionTopics(q.question).includes(t.id)));const subset=actual.map(s=>({...s,questions:s.questions.filter(q=>D.questionTopics(q.question).includes(t.id))})),words=D.wordRows(subset),m=subset.map(D.metrics),sum=k=>m.reduce((a,x)=>a+x[k],0);const dates=subset.flatMap(s=>s.questions.filter(q=>q.seenAt).map(q=>q.seenAt)).sort();return [t.name,actual.length,words.length,sum('solved'),sum('attempts')+' attempts; '+sum('hints')+' hints; '+sum('listens')+' listens',D.localTime(dates[0]),D.localTime(dates.at(-1)),words.filter(w=>w.needsPractice).map(w=>w.word).join(', ')||'-'];});card.append(table(['Topic','Studied sessions','Seen items','Correct','Support','First seen','Last seen','Needs practice'],data));}root.append(card);}
function sessionDetails(s){const root=$('content');root.replaceChildren(el('section',{class:'card'},el('div',{class:'row between'},el('h1',{},'Session details'),button('Back to history',render)),el('pre',{class:'summary'},D.parentSummary(s)),el('div',{class:'row'},button('Single-session JSON report',()=>download('rise-session-'+s.id+'.json',{kind:'single-session-report',session:s})),button('Copy summary',()=>copy(D.parentSummary(s))),s.status==='in-progress'?button('Resume',()=>openSession(s.id),'primary',locked()):null,s.status==='in-progress'?button('End this session early',async()=>{if(!confirm('End this session without marking unfinished questions correct?'))return;current=D.clone(s);route='quiz';await mutate(x=>D.endEarly(x));},'danger',locked()):null),el('p',{class:'help'},'Original snapshots from content '+s.libraryVersion+'. First correct is recorded exactly once; rendering this report adds no events.')));
  for(const [i,q]of s.questions.entries()){const card=el('section',{class:'card'},el('h2',{},(i+1)+'. '+q.question.word+' - '+D.outcome(q)),el('p',{},q.question.meaning),el('p',{},q.question.question),el('p',{class:'help'},q.question.lessonNames.join('; ')+' | seen '+D.localTime(q.seenAt)),el('p',{class:'help'},q.firstCorrect?'First correct: '+D.localTime(q.firstCorrect.at)+'; attempts to first correct: '+q.firstCorrect.attempts+'; hints: '+q.firstCorrect.hints+'; listens requested: '+q.firstCorrect.listens:'No first-correct record.'),table(['Submitted at','Answer','Outcome','Support at submission'],q.attempts.map(a=>[D.localTime(a.at),a.answer,a.correct?'Correct':'Try again',JSON.stringify(a.support)])),q.support.length?table(['Support at','Kind'],q.support.map(e=>[D.localTime(e.at),e.kind==='listen'?'listen ('+(e.trigger||'manual')+' request)':e.kind])):null);root.append(card);}}
function sessionsCSV(rows){download('rise-voca-sessions-filtered.csv',D.csv([['session_id','started_utc','started_local','timezone','last_activity_utc','ended_utc','status','selected_lessons','actually_studied_topics','mode','planned','seen','attempted','solved','skipped','unseen','first_try','unassisted_first_try','attempts','hints','listens_requested','active_ms','elapsed_ms'],...rows.map(s=>{const m=D.metrics(s);return [s.id,s.startedAt,D.localTime(s.startedAt),D.TIMEZONE,s.lastActivityAt,s.endedAt,s.status,s.lessonNames.join('; '),[...new Set(s.questions.filter(q=>q.seenAt).flatMap(q=>D.questionTopics(q.question)))].join('; '),s.mode,m.planned,m.seen,m.attempted,m.solved,m.skipped,m.unseen,m.firstTry,m.unassisted,m.attempts,m.hints,m.listens,m.activeMs,m.elapsedMs];})]),'text/csv;charset=utf-8');}
function wordsCSV(rows,search){const matches=new Set(D.wordRows(rows,search).map(w=>w.id));download('rise-voca-word-details-filtered.csv',D.csv([['session_id','item_id','word','meaning','source_topics','outcome','seen_utc','first_correct_utc','first_correct_local','timezone','attempts_to_first_correct','hints','listens','attempt_log_json'],...rows.flatMap(s=>s.questions.filter(q=>q.seenAt&&matches.has(q.question.itemId)).map(q=>[s.id,q.question.itemId,q.question.word,q.question.meaning,D.questionTopics(q.question).join('; '),D.outcome(q),q.seenAt,q.firstCorrect?.at,D.localTime(q.firstCorrect?.at),D.TIMEZONE,q.firstCorrect?.attempts,D.supportCounts(q).hints,D.supportCounts(q).listens,JSON.stringify(q.attempts)]))]),'text/csv;charset=utf-8');}
async function checkOffline(){try{const r=await navigator.serviceWorker?.getRegistration(),sw=r?.active;if(!sw)throw new Error('No active offline worker yet. Stay online and try again.');const status=await new Promise((resolve,reject)=>{const ch=new MessageChannel(),timeout=setTimeout(()=>reject(new Error('Offline check timed out.')),5000);ch.port1.onmessage=e=>{clearTimeout(timeout);resolve(e.data);};sw.postMessage({type:'CHECK_OFFLINE'},[ch.port2]);});offline=status.ready;$('offline-label').textContent=offline?'App/content + emoji/CSS: offline ready | Audio: device test needed':'Offline pack incomplete';if($('offline-detail'))$('offline-detail').textContent=offline?'All '+status.files+' app/content files verified present. Native emoji/CSS need no external image downloads. Audio has not been physically tested.':'Missing: '+status.missing.join(', ');return status;}catch(e){$('offline-label').textContent='Offline not verified: '+e.message;return {ready:false};}}
async function installPWA(){if(!('serviceWorker'in navigator)){$('offline-label').textContent='Offline installation is unavailable in this browser/context.';return;}try{const registration=await navigator.serviceWorker.register('./sw.js',{scope:'./',updateViaCache:'none'});const update=()=>{if(registration.waiting){$('update-status').hidden=false;$('update-status').textContent='A new version is ready. Save & pause, close all Rise_Voca windows, then reopen. Do not clear site data.';}};registration.addEventListener('updatefound',()=>registration.installing?.addEventListener('statechange',update));update();navigator.serviceWorker.addEventListener('controllerchange',()=>void checkOffline());await navigator.serviceWorker.ready;await checkOffline();}catch(e){$('offline-label').textContent='Offline install unavailable: '+e.message;}}
let ctrlAlone=false;
function editable(target){return target instanceof Element&&Boolean(target.closest('input,select,textarea,[contenteditable="true"]'));}
document.addEventListener('keydown',e=>{if(e.key==='Control'){ctrlAlone=!e.repeat&&!editable(e.target);return;}if(e.ctrlKey){ctrlAlone=false;return;}if(route!=='quiz'||editable(e.target)||e.altKey||e.metaKey||e.repeat)return;if(e.code==='Space'){e.preventDefault();listenQuestion();return;}if((e.key==='Enter'||e.key==='ArrowRight')&&current&&D.activeQuestion(current)?.firstCorrect){e.preventDefault();void mutate(s=>D.advance(s));return;}const key=/^Numpad([1-4])$/.exec(e.code)?.[1]||(/^[1-4]$/.test(e.key)?e.key:null);if(key){e.preventDefault();$('answer-'+(Number(key)-1))?.click();}});
document.addEventListener('keyup',e=>{if(e.key==='Control'){const go=ctrlAlone;ctrlAlone=false;if(go&&route==='quiz'&&!editable(e.target))void mutate(s=>D.addSupport(s,'hint'));}});
for(const type of ['pointerdown','keydown'])document.addEventListener(type,()=>lastInteraction=performance.now(),{passive:true});
window.addEventListener('blur',()=>ctrlAlone=false);
document.addEventListener('visibilitychange',()=>{lastTick=performance.now();if(document.visibilityState==='hidden'&&route==='quiz'&&current?.status==='in-progress'&&!current.paused)void mutate(s=>D.pause(s));});
window.addEventListener('pagehide',()=>{speech?.cancel();void store.release();});
window.addEventListener('pageshow',e=>{if(e.persisted){void store.acquire();store.interval=setInterval(()=>void store.acquire(),5000);}});
setInterval(()=>{if(route==='quiz'&&current?.status==='in-progress'&&!current.paused&&!locked()&&document.visibilityState==='visible'&&performance.now()-lastInteraction<60000)void mutate(s=>{s.lastActivityAt=D.nowISO();return true;},{paint:false});},10000);
async function main(){try{[library,registry,build,weeks]=await Promise.all(['./data/library.json','./data/illustrations.json','./BUILD_INFO.json','./data/weeks/index.json'].map(async path=>{const r=await fetch(path);if(!r.ok)throw new Error('Cannot load '+path);return r.json();}));D.validateLibrary(library);await store.open();prefs=await store.getPreferences();reviews=await store.readMeta('image-reviews',{});await reloadSessions();speech=new SpeechController({getPreferences:()=>prefs,onChange:updateSpeechControls,onStatus:msg=>{if($('speech-status'))$('speech-status').textContent=msg;else if(msg.includes('could not')||msg.includes('unavailable'))toast(msg);}});autoReader=new AutomaticClueReader({context:()=>({session:current,preferences:prefs,active:route==='quiz',visible:document.visibilityState==='visible',writable:!locked()}),speak:text=>speech.speak(text),record:async(sid,qid)=>{if(current?.id!==sid||D.activeQuestion(current)?.question.id!==qid)return false;return mutate(s=>D.addSupport(s,'listen',D.nowISO(),'automatic'),{paint:false});}});speech.start();$('build-label').textContent='Rise_Voca '+build.version+' | Private, on-device history';render();void installPWA();}catch(e){$('content').replaceChildren(el('section',{class:'card'},el('h1',{},'We could not open the lesson library'),el('p',{},e.message),el('p',{class:'help'},'Reconnect and reopen the app. Do not clear site data; existing history has not been deleted.')));}}
void main();